#!/bin/bash

set -e

cat << EOF > annotation.html
<p>this annotation was generated by a script in the source repo</p>
EOF

cat annotation.html | buildkite-agent annotate --style "success" --job "${BUILDKITE_STEP_ID}" --context "${BUILDKITE_STEP_ID}"
