#!/bin/bash

set -e
echo ".."
env
echo ".."

cat << EOF > annotation.html
<p>this annotation was generated by a script in the source repo</p>
EOF

cat annotation.html | buildkite-agent annotate --style "success" --context "${BUILDKITE_STEP_ID}"
